from enum import Enum


class MatchLevel(str, Enum):
    CONFIRMED_PLATFORM_ID = "CONFIRMED_PLATFORM_ID"
    SUSPECTED_SAME_NAME_JOB = "SUSPECTED_SAME_NAME_JOB"
    POSSIBLE_SAME_NAME_CATEGORY = "POSSIBLE_SAME_NAME_CATEGORY"
    HISTORICAL_SAME_NAME = "HISTORICAL_SAME_NAME"
