from enum import Enum


class StrEnum(str, Enum):
    pass


class Role(StrEnum):
    ADMIN = "ADMIN"
    HR_MANAGER = "HR_MANAGER"
    RECRUITER = "RECRUITER"


class Status(StrEnum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"


class PlatformIdScope(StrEnum):
    UNKNOWN = "UNKNOWN"
    ACCOUNT = "ACCOUNT"
    COMPANY = "COMPANY"
    GLOBAL = "GLOBAL"


class SourceIdentityType(StrEnum):
    PLATFORM_ID = "PLATFORM_ID"
    PAGE_HASH = "PAGE_HASH"
    ACCOUNT_NAME_JOB = "ACCOUNT_NAME_JOB"


class EngagementStage(StrEnum):
    CLAIMED = "CLAIMED"
    CONTACTED = "CONTACTED"
    RESUME_REQUESTED = "RESUME_REQUESTED"
    RESUME_RECEIVED = "RESUME_RECEIVED"
    INTERVIEW_INVITED = "INTERVIEW_INVITED"
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED"
    ON_HOLD = "ON_HOLD"
    REJECTED = "REJECTED"
    HIRED = "HIRED"
    CLOSED = "CLOSED"


class EventType(StrEnum):
    CLAIMED = "CLAIMED"
    CONTACTED = "CONTACTED"
    RESUME_REQUESTED = "RESUME_REQUESTED"
    RESUME_RECEIVED = "RESUME_RECEIVED"
    INTERVIEW_INVITED = "INTERVIEW_INVITED"
    INTERVIEW_RESCHEDULED = "INTERVIEW_RESCHEDULED"
    INTERVIEW_CANCELLED = "INTERVIEW_CANCELLED"
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED"
    ON_HOLD = "ON_HOLD"
    REJECTED = "REJECTED"
    CONTINUED_AFTER_WARNING = "CONTINUED_AFTER_WARNING"
    TRANSFER_REQUESTED = "TRANSFER_REQUESTED"
    TRANSFERRED = "TRANSFERRED"
    HIRED = "HIRED"
    CLOSED = "CLOSED"


class MatchLevel(StrEnum):
    CONFIRMED_PLATFORM_ID = "CONFIRMED_PLATFORM_ID"
    SUSPECTED_SAME_NAME_JOB = "SUSPECTED_SAME_NAME_JOB"
    POSSIBLE_SAME_NAME_CATEGORY = "POSSIBLE_SAME_NAME_CATEGORY"
    HISTORICAL_SAME_NAME = "HISTORICAL_SAME_NAME"


class ConflictStatus(StrEnum):
    OPEN = "OPEN"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    TRANSFER_REQUESTED = "TRANSFER_REQUESTED"
    TRANSFERRED = "TRANSFERRED"
    NOT_SAME_PERSON = "NOT_SAME_PERSON"
    CLOSED = "CLOSED"


class OutboxStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SENT = "SENT"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class RejectionScope(StrEnum):
    CURRENT_JOB = "CURRENT_JOB"
    COMPANY_LEVEL = "COMPANY_LEVEL"

