<script setup lang="ts">
import { onMounted, ref } from "vue";
import { ElMessage } from "element-plus";
import { useAuthStore } from "../stores/auth";
type Settings = { notify_on_contact: boolean; catchup_enabled: boolean; updated_at?: string; api_base_url?: string; web_url?: string; environment?: string };
const auth = useAuthStore(), loading = ref(true), saving = ref(false), data = ref<Settings>({ notify_on_contact: true, catchup_enabled: true });
async function load() { loading.value = true; try { data.value = await auth.client.request<Settings>("/admin/settings"); } catch (e) { ElMessage.error(e instanceof Error ? e.message : "加载设置失败"); } finally { loading.value = false; } }
async function save() { saving.value = true; try { data.value = await auth.client.request<Settings>("/admin/settings", { method: "PATCH", body: JSON.stringify({ notify_on_contact: data.value.notify_on_contact, catchup_enabled: data.value.catchup_enabled }) }); ElMessage.success("设置已保存，扩展刷新页面后生效"); } catch (e) { ElMessage.error(e instanceof Error ? e.message : "保存失败"); } finally { saving.value = false; } }
onMounted(load);
</script>
<template><div v-loading="loading" class="settings-page"><div class="page-heading"><div><p class="eyebrow">SYSTEM MANAGEMENT</p><h1>系统设置</h1><p>管理扩展连接、自动补扫和飞书通知策略</p></div><el-button type="primary" :loading="saving" @click="save">保存设置</el-button></div><section class="page-card settings-card"><div class="section-title"><div><h2>扩展连接</h2><p>连接地址由部署统一提供，管理员不可编辑</p></div><el-tag type="success">连接正常</el-tag></div><div class="setting-row"><div><strong>API 地址</strong><small>{{ data.api_base_url || '由当前后台部署提供' }}</small></div><el-tag type="info">只读</el-tag></div><div class="setting-row"><div><strong>管理后台地址</strong><small>{{ data.web_url || '当前后台地址' }}</small></div><el-tag type="info">只读</el-tag></div><div class="setting-row"><div><strong>运行环境</strong><small>{{ data.environment || 'production' }}</small></div></div></section><section class="page-card settings-card"><div class="section-title"><div><h2>自动补扫</h2><p>公司级开关，扩展会在读取配置后应用</p></div><el-switch v-model="data.catchup_enabled" /></div><el-alert type="info" :closable="false" show-icon title="开启后从上次成功同步的时间继续扫描，首次回看最近 48 小时；检测到点击、键盘或滚轮操作会暂停 30 秒。关闭开关不会删除补扫水位。" /></section><section class="page-card settings-card"><div class="section-title"><div><h2>飞书通知</h2><p>沿用现有协同通知策略</p></div><el-switch v-model="data.notify_on_contact" /></div></section></div></template>
